# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_ssi}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["seenmyfate"]
  s.date = %q{2010-11-07}
  s.description = %q{Easily add nginx sever side includes to you rails 3 app}
  s.email = %q{seenmyfate@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/ssi_controller.rb",
     "app/helpers/ssi_helper.rb",
     "config/routes.rb",
     "lib/generators/simple_ssi/USAGE",
     "lib/generators/simple_ssi/simple_ssi_generator.rb",
     "lib/generators/simple_ssi/templates/ssi_controller.rb",
     "lib/simple_ssi.rb",
     "lib/simple_ssi/engine.rb",
     "simple_ssi.gemspec"
  ]
  s.homepage = %q{http://github.com/seenmyfate/simple_ssi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Easily add nginx sever side includes to you rails 3 app}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

